//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomGeneratorInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomGeneratorInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string btAdd {
            get {
                return ResourceManager.GetString("btAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string btDelete {
            get {
                return ResourceManager.GetString("btDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Распределить.
        /// </summary>
        public static string btProcess {
            get {
                return ResourceManager.GetString("btProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Варианты ответа:.
        /// </summary>
        public static string lbAnswers {
            get {
                return ResourceManager.GetString("lbAnswers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопрос:.
        /// </summary>
        public static string lbQuestion {
            get {
                return ResourceManager.GetString("lbQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string lvName {
            get {
                return ResourceManager.GetString("lvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файл.
        /// </summary>
        public static string menuFile {
            get {
                return ResourceManager.GetString("menuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string menuFileExit {
            get {
                return ResourceManager.GetString("menuFileExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык интерфейса.
        /// </summary>
        public static string menuFileLanguage {
            get {
                return ResourceManager.GetString("menuFileLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        public static string menuFileLanguageEnglish {
            get {
                return ResourceManager.GetString("menuFileLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string menuFileLanguageRussian {
            get {
                return ResourceManager.GetString("menuFileLanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузить.
        /// </summary>
        public static string menuFileLoad {
            get {
                return ResourceManager.GetString("menuFileLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый.
        /// </summary>
        public static string menuFileNew {
            get {
                return ResourceManager.GetString("menuFileNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string menuFileSave {
            get {
                return ResourceManager.GetString("menuFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Генерация.
        /// </summary>
        public static string menuGenerate {
            get {
                return ResourceManager.GetString("menuGenerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В файл.
        /// </summary>
        public static string menuGenFile {
            get {
                return ResourceManager.GetString("menuGenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to С выводом.
        /// </summary>
        public static string menuGenOutput {
            get {
                return ResourceManager.GetString("menuGenOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string menuHelp {
            get {
                return ResourceManager.GetString("menuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string menuHelpAbout {
            get {
                return ResourceManager.GetString("menuHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string menuHelpHelp {
            get {
                return ResourceManager.GetString("menuHelpHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Разработчик:
        ///- Константин &apos;KonH&apos; Хитрых (konh@yandex.ru)
        ///Среда разработки:
        ///- Microsoft Visual Studio 2010
        ///Язык программирования:
        ///- C#
        ///Framework:
        ///- .NET Framework 4.0
        ///Интерфейс:
        ///- WPF
        ///Версия:
        ///- .
        /// </summary>
        public static string msgAbout {
            get {
                return ResourceManager.GetString("msgAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе.
        /// </summary>
        public static string msgAboutCaption {
            get {
                return ResourceManager.GetString("msgAboutCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы сохранены в файле:.
        /// </summary>
        public static string msgFileSave {
            get {
                return ResourceManager.GetString("msgFileSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to      Программа позволяет генерировать ответы на заданные вопросы с указанной вероятностью. Для добавления нового вопроса используйте кнопку &apos;Добавить&apos; в левом нижнем углу.
        ///    Новый вопрос отобразится в списке слева. При выборе вопроса возможно указать его текст и добавить новые варианты ответа (кнопка &apos;Добавить&apos; под текстом вопроса).
        ///    Вероятность выпадения каждого ответа указывается справа от ответа. Имеется возможность указать вероятности равномерно (кнопка &apos;Распределить&apos;).
        ///    Для получения ответов [rest of string was truncated]&quot;;.
        /// </summary>
        public static string msgHelp {
            get {
                return ResourceManager.GetString("msgHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помощь.
        /// </summary>
        public static string msgHelpCaption {
            get {
                return ResourceManager.GetString("msgHelpCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросы:.
        /// </summary>
        public static string msgQuestions {
            get {
                return ResourceManager.GetString("msgQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вопросов не найдено..
        /// </summary>
        public static string msgQuestionsNotFound {
            get {
                return ResourceManager.GetString("msgQuestionsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить файл при выходе?.
        /// </summary>
        public static string msgSaveFile {
            get {
                return ResourceManager.GetString("msgSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранение файла.
        /// </summary>
        public static string msgSaveFileCaption {
            get {
                return ResourceManager.GetString("msgSaveFileCaption", resourceCulture);
            }
        }
    }
}
